server:
  port: 8082
spring:
  application:
    name: cloud-test-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
logging:
  config: classpath:logback-spring-dev.xml
mybatis-plus:
  mapper-locations: classpath*:mapper/*
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/